<a href="https://colab.research.google.com/github/siddahant/Linear-Algebra-/blob/main/TDMAsolver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import math

In [ ]:
def SV(diagonalVector, subdiagonalVector,superdiagonalVector, m):
  subdiagonal_vector = []
  diagonal_vector = []
  superdiagonal_vector = [0]

  for i in range(m-2):
    subdiagonal_vector.append(subdiagonalVector)

  for k in range(m-1):
    diagonal_vector.append(diagonalVector)

  for j in range(m-1):
    superdiagonal_vector.append(superdiagonalVector)
  return  subdiagonal_vector, diagonal_vector, superdiagonal_vector


In [ ]:
def RHV(m,tw,tin):

  deltax=1/m
  rhs=[]
  for i in range(1, m):
    rhs.append(-(math.sin(2*math.pi*deltax*i)*50)*((1/m)**2))
  
  rhs[0]=rhs[0]+tw
  rhs[-1]=rhs[-1]+tin

  return rhs 


In [ ]:
RHV(8,5,60)

[4.44757282719801,
 -0.78125,
 -0.5524271728019903,
 -9.567553118338697e-17,
 0.5524271728019902,
 0.78125,
 60.55242717280199]

In [ ]:
def solver(a, b, c, d):
    '''
    a = subdiagonal vector
    b = diagonal vector 
    c = superdiagonal vector
    d= right hand side vector 
    
    '''
    n = len(b) # number of equations
    a, b, c, d = map(np.array, (a, b, c, d)) # copy arrays
    for i in range(1, n):
        m = a[i-1]/b[i-1]
        b[i] = b[i] - m*c[i-1] 
        d[i] = d[i] - m*d[i-1]
        	    
    x = b
    x[-1] = d[-1]/b[-1]

    for i in range(n-2, -1, -1):
        x[i] = (d[i]-c[i]*x[i+1])/b[i]

    del b, c, d # delete variables from memory

    return x

In [ ]:
def disp(size_of_a_matrix, diagonal, diagonalAbove, diagonalBelow):
   
    matrix = [[0 for j in range(size_of_a_matrix)]
              for i in range(size_of_a_matrix)]
      
    for k in range(size_of_a_matrix-1):
        matrix[k][k] = diagonal[k]
        matrix[k][k+1] = diagonalAbove[k]
        matrix[k+1][k] = diagonalBelow[k]
      
    matrix[size_of_a_matrix-1][size_of_a_matrix - 1] = diagonal[size_of_a_matrix-1]
   
    # so that the values will print row by row
    for row in matrix:
        print(row)
  
    return "this is the tridiagonal matrix"

In [ ]:
def main(size, tw, tin, diagonal, diagonalAbove, diagonalBelow):
  x=SV(2,-1,-1,size)
  disp(size-1,x[1],x[2],x[0])
  d=RHV(size,tw,tin)

  result = solver(x[0], x[1], x[2], d)
  
  return result


In [ ]:
main(8,5.0,60.0,2.0,-1.,-1.)


[2, 0, 0, 0, 0, 0, 0]
[-1, 2, -1, 0, 0, 0, 0]
[0, -1, 2, -1, 0, 0, 0]
[0, 0, -1, 2, -1, 0, 0]
[0, 0, 0, -1, 2, -1, 0]
[0, 0, 0, 0, -1, 2, -1]
[0, 0, 0, 0, 0, -1, 2]


array([ 2, 32, 63, 63, 63, 63, 62])

In [ ]:
#analytical 
k=8
for i in range(k):
  tx=(((math.sin(2*math.pi*(1/k)*i)) * (1/4*(math.pi**2))) + (55*(1/k)*i) + 5)
  print(tx)

5.0
13.61971604990972
21.21740110027234
27.36971604990972
32.5
37.63028395009028
43.78259889972766
51.38028395009028


In [ ]:
A = np.array([[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]],dtype=float) 
print(A)

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]


In [ ]:
A = np.array([[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]],dtype=float) 
d=[3.0978869674096927,-1.1755705045849467,1.1755705045849463,61.90211303259031]

print (np.linalg.solve(A, d))

[14.62361808 26.14934919 38.85065081 50.37638192]


In [ ]:
def solver(a, b, c, d):
    '''
    a = subdiagonal vector
    b = diagonal vector 
    c = superdiagonal vector
    d= right hand side vector 
        
    '''
    N = len(b) # number of equations
    a, b, c, d = map(np.array, (a, b, c, d)) # copy the array
    for i in range(2, N):
        factor = a[i]/b[i-1]
        b[i] = b[i] - factor*c[i-1]
        d[i] = d[i] - factor*d[i-1]

    x=b
    x[-1] = d[-1]/b[-1]

    for i in range(N-2, 0,-1):
        x[i] = (d[i]-c[i]*x[i+1])/b[i]

    del b, c, d # delete variables from memory

    return x

In [ ]:
def TDMAsolver(a, b, c, d):
    '''
    TDMA solver, a b c d can be NumPy array type or Python list type.
    refer to http://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm
    and to http://www.cfd-online.com/Wiki/Tridiagonal_matrix_algorithm_-_TDMA_(Thomas_algorithm)
    '''
    nf = len(d) # number of equations
    ac, bc, cc, dc = map(np.array, (a, b, c, d)) # copy arrays
    for it in range(1, nf):
        mc = ac[it-1]/bc[it-1]
        bc[it] = bc[it] - mc*cc[it-1] 
        dc[it] = dc[it] - mc*dc[it-1]
        	    
    xc = bc
    xc[-1] = dc[-1]/bc[-1]

    for il in range(nf-2, -1, -1):
        xc[il] = (dc[il]-cc[il]*xc[il+1])/bc[il]

    return xc


In [ ]:
a=[0,-1,-1,-1]
b=[-2.04,-2.04,-2.04,-2.04]
c=[-1,-1,-1,]
d=[40.8,.8,.8,200.8]
TDMAsolver(a,b,c,d)

array([   2.4214851 ,  -45.73982961,   92.50925241, -143.7790453 ])